name: testenv
channels:
  - conda-forge
  - defaults
dependencies:
  - arm_pyart
  - pip
  - numpy<2.2.0
  - scipy
  - matplotlib
  - netcdf4
  - pytest
  - pytest-mpl
  - pytest-cov
  - cartopy
  - cfgrib
  - eccodes
  - dask
  - distributed
  - cmweather
  - jax
  - jaxopt
