name: build-docs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# This job installs dependencies, build the website, and pushes it to `gh-pages`
jobs:
  deploy-website:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v5

      # Install dependencies
      - name: Setup Conda Environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: doc/environment_docs.yml
          activate-environment: pydda-docs
          auto-activate-base: false
          mamba-version: '*'
          use-mamba: true

      - name: Install PyDDA
        run: |
          pip install -e .

      # Build the website
      - name: Build the site
        run: |
          cd doc
          make html

      # Push the book's HTML to github-pages
      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3.8.0
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: doc/build/html
          cname: https://openradarscience.org/PyDDA
